### ISSUE TITLE
Synapse ACL reset checklist

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/synapse_acl_reset#6]
@aditigopalan here is a checklist for us to work through on Monday

- [x] Code review
- [x] Confirmed happy to procede

- [x] Set project ACLs
  - [x] ohsu: syn22093319
  - [x] bu: syn22124336
  - [x] vanderbilt: syn21050481
  - [x] dfci: syn23511954
  - [x] wustl: syn22255320
  - [x] duke: syn23511961
  - [x] stanford: syn23511964
  - [x] chop: syn22776798
  - [x] msk: syn23448901
  - [x] hms: syn22123910
  - [x] pcapp: syn23511984
  - [x] htapp: syn20834712
  - [x] srrs: syn25555889
  - [x] tnp_sardana: syn24984270
  - [x] tnp_tma: syn22041595
  - [x] tnp_casi: syn52861417

- [x] Reset non-project ACLs
  - [x] ohsu: syn22093319
  - [x] bu: syn22124336
  - [x] vanderbilt: syn21050481
  - [x] dfci: syn23511954
  - [x] wustl: syn22255320
  - [x] duke: syn23511961
  - [x] stanford: syn23511964
  - [x] chop: syn22776798
  - [x] msk: syn23448901
  - [x] hms: syn22123910
  - [x] pcapp: syn23511984
  - [x] htapp: syn20834712
  - [x] srrs: syn25555889
  - [x] tnp_sardana: syn24984270
  - [x] tnp_tma: syn22041595
  - [x] tnp_casi: syn52861417

- [x] Make released files public

- [ ] Check all happy

- [x] Invite FAIR data members to HTAN_DCC team
  - [x]   Loren Wolfe
  - [x] Anthony Williams
  - [x] Andrew Lamb
  - [x] Mialy Defelice
  - [x] Amy Heiser
  - [x] Milen Nikolov
  - [x] Lingling Peng
  - [x] Gianna Jordan

- [ ] post in slack channels to say to reach out with service desk tickets if they think they have lost access to any resources
  - [x] ohsu: syn22093319
  - [ ] bu: syn22124336
  - [x] vanderbilt: syn21050481
  - [ ] dfci: syn23511954
  - [ ] wustl: syn22255320
  - [ ] duke: syn23511961
  - [ ] stanford: syn23511964
  - [ ] chop: syn22776798
  - [ ] msk: syn23448901
  - [ ] hms: syn22123910
  - [ ] pcapp: syn23511984
  - [ ] htapp: syn20834712
  - [ ] srrs: syn25555889
  - [ ] tnp_sardana: syn24984270
  - [ ] tnp_tma: syn22041595
  - [ ] tnp_casi: syn52861417
- [ ] Report back to DCC

Query to check ACL resets: 
`SELECT projectId, COUNT(DISTINCT(benefactorId)) as n FROM syn20446927 WHERE benefactorId<> projectId GROUP BY projectId ORDER BY n DESC`

**Comment by aditigopalan** [comment]
re: code review [not immediate]

1. Error Handling

- It would be nice to have error handling around functions i.e `try-except` blocks around API calls (`get_acl` and `put_acl`) to catch potential errors and log them in `set_project_acl.py`
- There is already some error handling for Synapse API errors in the delete_acl function. We could consider adding similar error handling in other functions where API calls are made (`get_acl`, `verify_acl_inheritance`, and `reset_acls`).
- Same for other scripts 

2. Logging 

- We could use the logging module in python for better visibility/ potential debugging

**Comment by adamjtaylor** [comment]
We used `make_public_async.py` to make the entities public. This increases our throughput from ~1 it/s to ~ 8 it/s.

We made 13246 files public.
